/*
 Navicat Premium Data Transfer

 Source Server         : homestead
 Source Server Type    : MySQL
 Source Server Version : 80027
 Source Host           : 127.0.0.1:33060
 Source Schema         : plunge

 Target Server Type    : MySQL
 Target Server Version : 80027
 File Encoding         : 65001

 Date: 10/08/2022 06:42:21
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for categories
-- ----------------------------
DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
  id int unsigned NOT NULL AUTO_INCREMENT,
  name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  code varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  remark varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  user_id int unsigned NOT NULL DEFAULT '0',
  stock_count int unsigned NOT NULL DEFAULT '0',
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of categories
-- ----------------------------
BEGIN;
INSERT INTO categories VALUES (1, '20220725adminVol', '20220725adminVol', 'Head and shoulders or box pattern wrapped around MA20. Auto generated by Plunge ', 1, 0, '2022-07-30 21:01:04', '2022-07-30 21:01:04');
INSERT INTO categories VALUES (2, '20220725adminChips', '20220725adminChips', 'Getting chips.Auto generated by Plunge ', 1, 0, '2022-07-30 21:20:59', '2022-07-30 21:20:59');
INSERT INTO categories VALUES (21, 'BreakWithVol0803', 'BreakWithVol0803', 'Head and shoulders or box pattern wrapped around MA20. Auto generated by Plunge ', 1, 0, '2022-08-06 19:37:11', '2022-08-06 19:37:11');
INSERT INTO categories VALUES (22, 'GetChips0803', 'GetChips0803', 'Getting chips.Auto generated by Plunge ', 1, 0, '2022-08-06 19:37:56', '2022-08-06 19:37:56');
INSERT INTO categories VALUES (23, 'Stars0803', 'Stars0803', 'Continuous stars.Auto generated by Plunge ', 1, 0, '2022-08-06 19:38:08', '2022-08-06 19:38:08');
INSERT INTO categories VALUES (24, 'SuportWithGap0803', 'SuportWithGap0803', 'Support at the gap .Auto generated by Plunge ', 1, 0, '2022-08-06 19:38:28', '2022-08-06 19:38:28');
INSERT INTO categories VALUES (26, '0806', '', '0806selected', 1, 0, '2022-08-06 20:04:32', '2022-08-06 20:04:32');
INSERT INTO categories VALUES (27, 'BreakWithVol0804', 'BreakWithVol0804', 'Head and shoulders or box pattern wrapped around MA20. Auto generated by Plunge ', 1, 0, '2022-08-07 08:25:31', '2022-08-07 08:25:31');
INSERT INTO categories VALUES (28, 'GetChips0804', 'GetChips0804', 'Getting chips.Auto generated by Plunge ', 1, 0, '2022-08-07 08:26:21', '2022-08-07 08:26:21');
INSERT INTO categories VALUES (29, 'Stars0804', 'Stars0804', 'Continuous stars.Auto generated by Plunge ', 1, 0, '2022-08-07 08:26:36', '2022-08-07 08:26:36');
INSERT INTO categories VALUES (30, 'SuportWithGap0804', 'SuportWithGap0804', 'Support at the gap .Auto generated by Plunge ', 1, 0, '2022-08-07 08:26:58', '2022-08-07 08:26:58');
INSERT INTO categories VALUES (31, 'BreakWithVol0808', 'BreakWithVol0808', 'Head and shoulders or box pattern wrapped around MA20. Auto generated by Plunge ', 1, 0, '2022-08-10 00:00:05', '2022-08-10 00:00:05');
INSERT INTO categories VALUES (32, 'GetChips0808', 'GetChips0808', 'Getting chips.Auto generated by Plunge ', 1, 0, '2022-08-10 00:01:02', '2022-08-10 00:01:02');
INSERT INTO categories VALUES (33, 'Stars0808', 'Stars0808', 'Continuous stars.Auto generated by Plunge ', 1, 0, '2022-08-10 00:01:27', '2022-08-10 00:01:27');
INSERT INTO categories VALUES (34, 'SuportWithGap0808', 'SuportWithGap0808', 'Support at the gap .Auto generated by Plunge ', 1, 0, '2022-08-10 00:01:53', '2022-08-10 00:01:53');
INSERT INTO categories VALUES (35, '0810', '', NULL, 1, 0, '2022-08-10 00:11:53', '2022-08-10 00:11:53');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
