/*
 Navicat Premium Data Transfer

 Source Server         : homestead
 Source Server Type    : MySQL
 Source Server Version : 80027
 Source Host           : 127.0.0.1:33060
 Source Schema         : plunge

 Target Server Type    : MySQL
 Target Server Version : 80027
 File Encoding         : 65001

 Date: 03/08/2022 06:53:13
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for categories
-- ----------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_id` int unsigned NOT NULL DEFAULT '0',
  `stock_count` int unsigned NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of categories
-- ----------------------------
BEGIN;
INSERT INTO `categories` VALUES (1, '20220725adminVol', '20220725adminVol', 'Head and shoulders or box pattern wrapped around MA20. Auto generated by Plunge ', 1, 0, '2022-07-30 21:01:04', '2022-07-30 21:01:04');
INSERT INTO `categories` VALUES (2, '20220725adminChips', '20220725adminChips', 'Getting chips.Auto generated by Plunge ', 1, 0, '2022-07-30 21:20:59', '2022-07-30 21:20:59');
INSERT INTO `categories` VALUES (3, 'test2', '', '222', 1, 0, '2022-08-01 22:46:50', '2022-08-01 22:46:50');
COMMIT;

-- ----------------------------
-- Table structure for stocks
-- ----------------------------
DROP TABLE IF EXISTS `stocks`;
CREATE TABLE `stocks` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `price_id` int unsigned NOT NULL,
  `day` date NOT NULL,
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int unsigned NOT NULL,
  `category_id` int unsigned NOT NULL,
  `pattern` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `market` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `score` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `stocks_cate_ind` (`category_id`,`code`) USING BTREE,
  KEY `stocks_code_index` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=191 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of stocks
-- ----------------------------
BEGIN;
INSERT INTO `stocks` VALUES (90, 1, '2022-07-25', '3964', 1, 1, '1', '2', 'auto', '2022-07-30 21:19:58', NULL, 0);
INSERT INTO `stocks` VALUES (96, 0, '2022-07-25', '4570', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:00', NULL, 0);
INSERT INTO `stocks` VALUES (97, 0, '2022-07-25', '4781', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:00', NULL, 0);
INSERT INTO `stocks` VALUES (98, 0, '2022-07-25', '5337', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:01', NULL, 0);
INSERT INTO `stocks` VALUES (101, 0, '2022-07-25', '6550', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:03', NULL, 0);
INSERT INTO `stocks` VALUES (102, 0, '2022-07-25', '6629', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:04', NULL, 0);
INSERT INTO `stocks` VALUES (106, 0, '2022-07-25', '7525', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:06', NULL, 0);
INSERT INTO `stocks` VALUES (110, 0, '2022-07-25', '7841', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:07', NULL, 0);
INSERT INTO `stocks` VALUES (111, 0, '2022-07-25', '8117', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:08', NULL, 0);
INSERT INTO `stocks` VALUES (112, 0, '2022-07-25', '8890', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:09', NULL, 0);
INSERT INTO `stocks` VALUES (115, 1, '2022-07-25', '3161', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:14', NULL, 0);
INSERT INTO `stocks` VALUES (122, 1, '2022-07-25', '4374', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:17', NULL, 0);
INSERT INTO `stocks` VALUES (124, 0, '2022-07-25', '4389', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:18', NULL, 0);
INSERT INTO `stocks` VALUES (125, 0, '2022-07-25', '4413', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:18', NULL, 0);
INSERT INTO `stocks` VALUES (126, 0, '2022-07-25', '4445', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:18', NULL, 0);
INSERT INTO `stocks` VALUES (127, 0, '2022-07-25', '4978', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:19', NULL, 0);
INSERT INTO `stocks` VALUES (130, 0, '2022-07-25', '6236', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:21', NULL, 0);
INSERT INTO `stocks` VALUES (131, 0, '2022-07-25', '6255', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:21', NULL, 0);
INSERT INTO `stocks` VALUES (132, 0, '2022-07-25', '6424', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:22', NULL, 0);
INSERT INTO `stocks` VALUES (133, 0, '2022-07-25', '7041', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:23', NULL, 0);
INSERT INTO `stocks` VALUES (134, 0, '2022-07-25', '7172', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:24', NULL, 0);
INSERT INTO `stocks` VALUES (139, 0, '2022-07-25', '7774', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:25', NULL, 0);
INSERT INTO `stocks` VALUES (140, 0, '2022-07-25', '7791', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:25', NULL, 0);
INSERT INTO `stocks` VALUES (141, 0, '2022-07-25', '7985', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:26', NULL, 0);
INSERT INTO `stocks` VALUES (146, 1, '2022-07-25', '3802', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:34', NULL, 0);
INSERT INTO `stocks` VALUES (147, 1, '2022-07-25', '3851', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:34', NULL, 0);
INSERT INTO `stocks` VALUES (148, 1, '2022-07-25', '3913', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:35', NULL, 0);
INSERT INTO `stocks` VALUES (150, 1, '2022-07-25', '4235', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:35', NULL, 0);
INSERT INTO `stocks` VALUES (153, 0, '2022-07-25', '4668', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:37', NULL, 0);
INSERT INTO `stocks` VALUES (154, 0, '2022-07-25', '5918', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:38', NULL, 0);
INSERT INTO `stocks` VALUES (155, 0, '2022-07-25', '5974', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:38', NULL, 0);
INSERT INTO `stocks` VALUES (156, 0, '2022-07-25', '5999', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:38', NULL, 0);
INSERT INTO `stocks` VALUES (157, 0, '2022-07-25', '6180', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:39', NULL, 0);
INSERT INTO `stocks` VALUES (158, 0, '2022-07-25', '6360', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:40', NULL, 0);
INSERT INTO `stocks` VALUES (159, 0, '2022-07-25', '6488', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:40', NULL, 0);
INSERT INTO `stocks` VALUES (160, 0, '2022-07-25', '6647', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:40', NULL, 0);
INSERT INTO `stocks` VALUES (161, 0, '2022-07-25', '6737', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:41', NULL, 0);
INSERT INTO `stocks` VALUES (162, 0, '2022-07-25', '6897', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:41', NULL, 0);
INSERT INTO `stocks` VALUES (163, 0, '2022-07-25', '7199', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:42', NULL, 0);
INSERT INTO `stocks` VALUES (164, 0, '2022-07-25', '7217', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:42', NULL, 0);
INSERT INTO `stocks` VALUES (165, 0, '2022-07-25', '7265', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:42', NULL, 0);
INSERT INTO `stocks` VALUES (166, 0, '2022-07-25', '7369', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:42', NULL, 0);
INSERT INTO `stocks` VALUES (167, 0, '2022-07-25', '7375', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:42', NULL, 0);
INSERT INTO `stocks` VALUES (168, 0, '2022-07-25', '7771', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:43', NULL, 0);
INSERT INTO `stocks` VALUES (169, 0, '2022-07-25', '7983', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:44', NULL, 0);
INSERT INTO `stocks` VALUES (170, 0, '2022-07-25', '8115', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:45', NULL, 0);
INSERT INTO `stocks` VALUES (171, 0, '2022-07-25', '9233', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:46', NULL, 0);
INSERT INTO `stocks` VALUES (172, 0, '2022-07-25', '9353', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:46', NULL, 0);
INSERT INTO `stocks` VALUES (174, 0, '2022-07-25', '9976', 1, 1, '1', '2', 'auto', '2022-07-30 21:20:48', NULL, 0);
INSERT INTO `stocks` VALUES (176, 0, '2022-07-25', '6181', 1, 2, '1', '2', 'auto', '2022-07-30 21:20:55', NULL, 0);
INSERT INTO `stocks` VALUES (177, 0, '2022-07-25', '9418', 1, 2, '1', '2', 'auto', '2022-07-30 21:20:58', NULL, 0);
INSERT INTO `stocks` VALUES (179, 2, '2022-07-31', '3986', 1, 1, '1', '2', 'auto', '2022-07-31 10:19:16', '2022-07-31 10:19:16', 3);
INSERT INTO `stocks` VALUES (180, 2, '2022-07-31', '4016', 1, 1, '1', '2', 'auto', '2022-07-31 10:47:26', '2022-07-31 10:47:26', 1);
INSERT INTO `stocks` VALUES (181, 2, '2022-07-31', '4052', 1, 1, '1', '2', 'auto', '2022-07-31 10:47:33', '2022-07-31 10:47:33', 2);
INSERT INTO `stocks` VALUES (182, 0, '2022-07-31', '3628', 1, 2, '1', '2', 'auto', '2022-07-31 13:06:20', '2022-07-31 13:06:20', 3);
INSERT INTO `stocks` VALUES (183, 2, '2022-07-31', '4059', 1, 1, '1', '2', 'auto', '2022-07-31 14:15:32', '2022-07-31 14:15:32', 4);
INSERT INTO `stocks` VALUES (185, 0, '2022-08-01', '1992', 1, 1, '1', '2', 'auto', '2022-08-01 22:23:41', '2022-08-01 22:23:41', 3);
INSERT INTO `stocks` VALUES (186, 0, '2022-08-01', '3557', 1, 1, '1', '2', 'auto', '2022-08-01 22:23:53', '2022-08-01 22:23:53', 5);
INSERT INTO `stocks` VALUES (188, 0, '2022-08-01', '3333', 1, 3, '1', '2', 'by category', '2022-08-01 22:47:24', '2022-08-01 22:47:24', 5);
INSERT INTO `stocks` VALUES (189, 0, '2022-08-01', '3333', 1, 2, '1', '2', 'by category', '2022-08-01 22:47:24', '2022-08-01 22:47:24', 5);
INSERT INTO `stocks` VALUES (190, 0, '2022-08-01', '3333', 1, 1, '1', '2', 'by category', '2022-08-01 22:47:24', '2022-08-01 22:47:24', 5);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
